### ISSUE TITLE
SingleInstance with Key doesn't register as implemented interfaces

### ISSUE THREAD

**Issue by shawnshaddock** [soxtoby/Autofac.AttributeExtensions#2] opened 2018-04-27 23:41 UTC
When using the SingleInstanceAttribute with a Key, the service will not be registered as implemented interfaces. If I have a FooService that implements IFooService, and I put the SingleInstanceAttribute on the service using a Key, I cannot resolve the service by IFooService. However if I don't use a Key, it works as expected.

**Comment by soxtoby** [comment] 2018-04-28 02:54
Thanks for the bug report, @shawnshaddock.

Normally if you're providing a key for a service, you'd have multiple implementations of its interface, which you'd resolve via Autofac's `IIndex<,>` type. If multiple types are registered as `IFooService` then resolving just a single one, without a key, will give unpredictable results.

If one of the implementations is intended as a default, then I'd recommend providing a `Name`, such as "default", and resolving it with that name. You could also add a manual registration for the interface that resolves the default implementation in one of the following ways:
```cs
containerBuilder.Register(c => c.Resolve<FooService>()).As<IFooService>();
containerBuilder.Register(c => c.ResolveKeyed<IFooService>(myKey)).As<IFooService>();
containerBuilder.Register(c => c.ResolveNamed<IFooService>("default")).As<IFooService>();
```

Let me know if that helps.

**Comment by shawnshaddock** [comment] 2018-04-28 19:36
In my particular scenario I am registering multiple implementations of IFooService with a key, but I need to also be able resolve them all.

```C#
var services = container.Resolve<IEnumerable<IFooService>>();
```

But when I try to resolve them like that, I get no services back.

**Comment by soxtoby** [comment] 2018-04-30 02:27
The current behaviour is by design, but mostly because that scenario didn't occur to me for some reason. I think I assumed that `IIndex<,>` would let you iterate over the implementations, but it doesn't.

I don't see any likely issues with registering keyed services as un-keyed as well, so I'll make the change.

**Closed as completed** 2018-04-30 09:51 UTC
Labels: enhancement

**Comment by soxtoby** [comment] 2018-04-30 10:00
Change has been made, and I've pushed a new version to NuGet.

**Comment by shawnshaddock** [comment] 2018-05-01 02:04
Thanks, I've tested the new NuGet package and it's working as intended. I also tested disabling the functionality using

```C#
AsImplementedInterfaces = false
```
And it works as intended. Good job!
